resources:
- name: image
  type: docker-image
  source:
    repository: jacopen/yj
    username: ((username))
    password: ((password))
- name: repo
  type: git
  source:
    uri: https://github.com/jacopen/docker-yj

jobs:
- name: build-and-push-image
  plan:
  - get: repo
    trigger: true
  - put: image
    params: {build: repo}

